WITH RECURSIVE FULL_HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM FULL_HOURS WHERE HOUR < 23
)

SELECT F.HOUR AS HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM FULL_HOURS F LEFT JOIN ANIMAL_OUTS A ON (HOUR(A.DATETIME) = F.HOUR) 
GROUP BY F.HOUR
ORDER BY HOUR;